/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.Administration;

import javax.swing.table.DefaultTableModel;
import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Organization.AssignmentDonation;

import finalprojectUserInterface.MainJFrameForm;
import javax.swing.JOptionPane;


/**
 *
 * @author sneha
 */
public class ManageDonations extends javax.swing.JPanel {

    /**
     * Creates new form ManageDonations
     */
    MainJFrameForm MainLoginPage;
    //FirebaseHelper firebaseHelper;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;

    public ManageDonations(MainJFrameForm MainLoginPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLoginPage = MainLoginPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        populateDonationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonations = new javax.swing.JTable();
        btn_UpdateStatus = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        tblDonations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Category", "Item name", "Status", "Donation Enterprise", "Receiver Entity", "Receiver Name", "Donar name", "Donor Manager", "Receiver Doctor", "Delivery Agent Name", "Report", "Id"
            }
        ));
        jScrollPane1.setViewportView(tblDonations);

        btn_UpdateStatus.setBackground(new java.awt.Color(255, 102, 102));
        btn_UpdateStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_UpdateStatus.setForeground(new java.awt.Color(255, 255, 255));
        btn_UpdateStatus.setText("Update Status");
        btn_UpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_UpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_UpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateStatusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDonations.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDonations.getModel();
        String id = model.getValueAt(selectedRow, 12).toString();
        System.out.println(" handler uname: " + id);

        for(AssignmentDonation de : operatingSystem.getAssignmentDonationList()){
            try{
                if(de.getUserId().equals(id)){
                    de.setStatusDonation(model.getValueAt(selectedRow, 3).toString());
                }
            }catch(Exception e){

            }
        }

        dB4OUtility.storeSystem(operatingSystem);
        JOptionPane.showMessageDialog(this, "Updated Status");

    }//GEN-LAST:event_btn_UpdateStatusActionPerformed


    private void populateDonationTable() {
        DefaultTableModel model = (DefaultTableModel) tblDonations.getModel();
        model.setRowCount(0);
        System.out.println("populateDonationtable");
        for (AssignmentDonation d : operatingSystem.getAssignmentDonationList()) {

            Object[] row = new Object[13];
            row[0] = d.getItem();
            row[1] = d.getCategory();
            row[2] = d.getEntityName();
            row[3] = d.getStatusDonation();
            try {
                row[4] = d.getDonEnterpriseClass().getNameEnterprise();
            } catch (Exception e) {

            }

            try {
                row[5] = d.getRecEnterpriseClass().getNameEnterprise();
            } catch (Exception e) {

            }
            try {
                row[6] = d.getRecRecepient().getNamePerson();
            } catch (Exception e) {

            }
            try {
                row[7] = d.getDonRecepient().getNamePerson();
            } catch (Exception e) {

            }
            try {
            row[8] = d.getDonManager().getNamePerson();
            }catch (Exception e) {

            }
            try {
            row[9] = d.getRecManager().getNamePerson();
            }catch (Exception e) {

            }
            try{
            row[10] = d.getDeliveryAgent().getNamePerson();
            }catch (Exception e) {

            }
            try {
            row[11] = d.getReportDonation();
            }catch (Exception e) {

            }
            try {
            row[12] = d.getUserId();
            }catch (Exception e) {

            }

            model.addRow(row);

        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_UpdateStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDonations;
    // End of variables declaration//GEN-END:variables
}
