/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.NGOInterface.LoginPage.NGOAdminLoginPages;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.NGO.NGOClass;
import finalprojectBackend.Enterprise.NGO.Manager;
import finalprojectBackend.Enterprise.NGO.Recepient;
import finalprojectBackend.Organization.AssignmentDonation;
import finalprojectBackend.Enterprise.NGO.Caretaker;
import finalprojectUserInterface.MainJFrameForm;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author sneha
 */
public class AdminPageforItemDonation extends javax.swing.JPanel {

    /**
     * Creates new form AdminPageforItemDonation
     */
    MainJFrameForm MainLoginPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    NGOClass ngo;

    public AdminPageforItemDonation(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem, NGOClass h) {
        initComponents();
        System.out.println("AdminDonateItem() init");
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.ngo = h;
        
        for (Manager d : operatingSystem.getManagerDirectory()) {

            if (d.getNGOName().equals(ngo.getNameEnterprise())) {
                manager_cmb.addItem(d.getpName());
            }

        }
        
        for(Recepient pa : operatingSystem.getRecepientDirectory() ){
            if( pa.getNGOName().equals(ngo.getNameEnterprise())){
                donar_txt.addItem(pa.getpName());
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manager_lbl = new javax.swing.JLabel();
        manager_cmb = new javax.swing.JComboBox<>();
        donar_lbl = new javax.swing.JLabel();
        donar_txt = new javax.swing.JComboBox<>();
        type_lbl = new javax.swing.JLabel();
        cat_lbl = new javax.swing.JLabel();
        type_txt = new javax.swing.JTextField();
        itemname_lbl = new javax.swing.JLabel();
        cat_txt = new javax.swing.JTextField();
        item_txt = new javax.swing.JTextField();
        addentity_btn = new javax.swing.JButton();
        temTiitle_lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manager_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manager_lbl.setText("Manager:");
        jPanel1.add(manager_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        manager_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        manager_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manager_cmbActionPerformed(evt);
            }
        });
        jPanel1.add(manager_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 190, -1));

        donar_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        donar_lbl.setText("Donar:");
        jPanel1.add(donar_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        donar_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jPanel1.add(donar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 190, -1));

        type_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type_lbl.setText("Type:");
        jPanel1.add(type_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        cat_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cat_lbl.setText("Category:");
        jPanel1.add(cat_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));
        jPanel1.add(type_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 190, -1));

        itemname_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemname_lbl.setText("Item Name:");
        jPanel1.add(itemname_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, 20));
        jPanel1.add(cat_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 190, -1));
        jPanel1.add(item_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 190, -1));

        addentity_btn.setBackground(new java.awt.Color(255, 102, 102));
        addentity_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addentity_btn.setText("Add Donation Entity");
        addentity_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addentity_btnActionPerformed(evt);
            }
        });
        jPanel1.add(addentity_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 188, 40));

        temTiitle_lbl.setBackground(new java.awt.Color(255, 255, 255));
        temTiitle_lbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        temTiitle_lbl.setText("Addition to NGO Donation");
        jPanel1.add(temTiitle_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addentity_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addentity_btnActionPerformed
        // TODO add your handling code here:

        AssignmentDonation de = new AssignmentDonation();
        de.setEntityName(item_txt.getText().toString());
        Random rand = new Random();
        de.setUserId( String.format("%04d", rand.nextInt(10000)));
        de.setDonEnterpriseClass(ngo);
        de.setCategory(cat_txt.getText().toString());
        de.setItem(type_txt.getText().toString());
        de.setDonManager(operatingSystem.getManagerByUserName(manager_cmb.getSelectedItem().toString()));
        de.setDonRecepient(operatingSystem.getReceiverByUserName(donar_txt.getSelectedItem().toString()));
        de.setStatusDonation("available");
        //        System.out.println("dede: "+de.getDonorDoctor().getName());
        operatingSystem.addDonationAssignment(de);

        dB4OUtility.storeSystem(operatingSystem);
        JOptionPane.showMessageDialog(this, "Entity added!");

    }//GEN-LAST:event_addentity_btnActionPerformed

    private void manager_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manager_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manager_cmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addentity_btn;
    private javax.swing.JLabel cat_lbl;
    private javax.swing.JTextField cat_txt;
    private javax.swing.JLabel donar_lbl;
    private javax.swing.JComboBox<String> donar_txt;
    private javax.swing.JTextField item_txt;
    private javax.swing.JLabel itemname_lbl;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> manager_cmb;
    private javax.swing.JLabel manager_lbl;
    private javax.swing.JLabel temTiitle_lbl;
    private javax.swing.JLabel type_lbl;
    private javax.swing.JTextField type_txt;
    // End of variables declaration//GEN-END:variables
}
