/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.NGOInterface;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.NGO.NGOClass;
import finalprojectBackend.Enterprise.NGO.Caretaker;
import finalprojectUserInterface.MainJFrameForm;
import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author sneha
 */
public class CaretakerSignUp extends javax.swing.JPanel {

    /**
     * Creates new form CaretakerSignUp
     */
    Random rand = new Random();
    
    boolean emptyValidationStatus = true;
    boolean validationCheck = true;
    
    
    MainJFrameForm MainLoginPage;
    //FirebaseHelper firebaseHelper;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    public CaretakerSignUp(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        for(NGOClass h: operatingSystem.getNGODirectory().getListOfNGO()){
            ngo_list.addItem(h.getNameEnterprise());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reg_txt = new javax.swing.JTextField();
        City_txt = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        uname_lbl = new javax.swing.JLabel();
        city_txt = new javax.swing.JTextField();
        uname_txt = new javax.swing.JTextField();
        state_txt = new javax.swing.JLabel();
        pswd_lbl = new javax.swing.JLabel();
        txt_state = new javax.swing.JTextField();
        pwd_txt = new javax.swing.JPasswordField();
        zip_lbl = new javax.swing.JLabel();
        address_lbl = new javax.swing.JLabel();
        zip_txt = new javax.swing.JTextField();
        add_txt = new javax.swing.JTextField();
        signup_btn = new javax.swing.JButton();
        lbl_admintitle = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        lbl_reg = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        ngo_list = new javax.swing.JComboBox<>();
        gender = new javax.swing.JLabel();
        gender_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dob_txt = new javax.swing.JTextField();
        contact_lbl = new javax.swing.JLabel();
        Contact_txt = new javax.swing.JTextField();
        lbl_ngo = new javax.swing.JLabel();
        gen_cmb = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(reg_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 216, -1));

        City_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        City_txt.setText("City:");
        jPanel1.add(City_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));
        jPanel1.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 216, -1));

        uname_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uname_lbl.setText("Username:");
        jPanel1.add(uname_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(city_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 216, -1));
        jPanel1.add(uname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 216, -1));

        state_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        state_txt.setText("State:");
        jPanel1.add(state_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        pswd_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pswd_lbl.setText("Password:");
        jPanel1.add(pswd_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel1.add(txt_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 216, -1));
        jPanel1.add(pwd_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 216, -1));

        zip_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zip_lbl.setText("Zip Code:");
        jPanel1.add(zip_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        address_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        address_lbl.setText("Address:");
        jPanel1.add(address_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));
        jPanel1.add(zip_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 216, -1));
        jPanel1.add(add_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 216, -1));

        signup_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signup_btn.setText("Sign Up");
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });
        jPanel1.add(signup_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 87, -1));

        lbl_admintitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_admintitle.setText("Create Caretaker Profile");
        jPanel1.add(lbl_admintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 87, -1));

        lbl_reg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_reg.setText("Registered No.:");
        jPanel1.add(lbl_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        name_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name_lbl.setText("Name:");
        jPanel1.add(name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        ngo_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jPanel1.add(ngo_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 216, -1));

        gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gender.setText("Gender:");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel1.add(gender_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 84, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("DOB:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        jPanel1.add(dob_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 90, -1));

        contact_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contact_lbl.setText("Contact:");
        jPanel1.add(contact_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        jPanel1.add(Contact_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 216, -1));

        lbl_ngo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_ngo.setText("NGO:");
        jPanel1.add(lbl_ngo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 60, 20));

        gen_cmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gen_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel1.add(gen_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 216, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        // TODO add your handling code here:
        try {
            if(EmpytyFieldValidation())
            {
                if(RegexValidation())
                {
                    String address = add_txt.getText() + "," + city_txt.getText() + "," + txt_state.getText() + "," + zip_txt.getText();
                    int id = rand.nextInt(99);
                    //Nurse nurse = new Caretaker(txtFullName.getText(), txtNo.getText(), address, txtUsrName.getText(), txtPass.getText(), txtGender.getText(), txtDOB.getText(), new Date(),jComboBox1.getSelectedItem().toString());
                    Caretaker nurse = new Caretaker(uname_txt.getText(), pwd_txt.getText(), String.valueOf(id), name_txt.getText(), address, gen_cmb.getSelectedItem().toString(), reg_txt.getText(), new Date(), ngo_list.getSelectedItem().toString());

                    operatingSystem.addCaretaker(nurse);
                    dB4OUtility.storeSystem(operatingSystem);

                    MainJFrameForm suc = new MainJFrameForm();
                    ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                    suc.setVisible(true);
                }
                else
                    {
                        JOptionPane.showMessageDialog(this,"Some Error in entered data.Please check over the red fields to know more.");
                        validationCheck=true;
                    }
            }
            else{
                    JOptionPane.showMessageDialog(this,"Data Cant be empty. Please check over the red fields to know more.");
                    emptyValidationStatus=true;
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Patient not registered, Try again");
             emptyValidationStatus=true;
        }
        
    }//GEN-LAST:event_signup_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    
    private boolean RegexValidation() {
    if(!name_txt.getText().matches("^[a-zA-Z ]+$"))
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(!Contact_txt.getText().matches("^[0-9]{10}$"))
        {
            Contact_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            Contact_txt.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }


        if(!zip_txt.getText().matches("^[0-9]{5}$"))
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            zip_txt.setToolTipText("Please enter a 5 digit number");
            validationCheck=false;
        }

        if(!reg_txt.getText().matches("^[0-9]{10}$"))
        {
            reg_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            reg_txt.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }

        return validationCheck;


    }   


    private boolean EmpytyFieldValidation() {
        if(add_txt.getText().equals(null) || add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            add_txt.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!add_txt.getText().equals(null) && !add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(city_txt.getText().equals(null) || city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            city_txt.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!city_txt.getText().equals(null) && !city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(name_txt.getText().equals(null) || name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!name_txt.getText().equals(null) && !name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(pwd_txt.getText().equals(null) || pwd_txt.getText().trim().isEmpty() )
        {
            pwd_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            pwd_txt.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!pwd_txt.getText().equals(null) && !pwd_txt.getText().trim().isEmpty() )
        {
            pwd_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txt_state.getText().equals(null) || txt_state.getText().trim().isEmpty() )
        {
            txt_state.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txt_state.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txt_state.getText().equals(null) && !txt_state.getText().trim().isEmpty() )
        {
            txt_state.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(uname_txt.getText().equals(null) || uname_txt.getText().trim().isEmpty() )
            {
                uname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                uname_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!uname_txt.getText().equals(null) && !uname_txt.getText().trim().isEmpty() )
        {
            uname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(zip_txt.getText().equals(null) || zip_txt.getText().trim().isEmpty() )
            {
                zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                zip_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!zip_txt.getText().equals(null) && !zip_txt.getText().trim().isEmpty() )
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(reg_txt.getText().equals(null) || reg_txt.getText().trim().isEmpty() )
            {
                reg_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                reg_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!reg_txt.getText().equals(null) && !reg_txt.getText().trim().isEmpty() )
        {
            reg_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(Contact_txt.getText().equals(null) || Contact_txt.getText().trim().isEmpty() )
            {
                Contact_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                Contact_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!Contact_txt.getText().equals(null) && !Contact_txt.getText().trim().isEmpty() )
        {
            Contact_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        
//        if(gender_txt.getText().equals(null) || gender_txt.getText().trim().isEmpty() )
//            {
//                gender_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
//                gender_txt.setToolTipText("This Field Cannot be empty");
//                emptyValidationStatus= false;
//            }
//        if(!gender_txt.getText().equals(null) && !gender_txt.getText().trim().isEmpty() )
//        {
//            gender_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
//        }
        
        if(dob_txt.getText().equals(null) || dob_txt.getText().trim().isEmpty() )
            {
                dob_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                dob_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!dob_txt.getText().equals(null) && !dob_txt.getText().trim().isEmpty() )
        {
            dob_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        
        return emptyValidationStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel City_txt;
    private javax.swing.JTextField Contact_txt;
    private javax.swing.JTextField add_txt;
    private javax.swing.JLabel address_lbl;
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField city_txt;
    private javax.swing.JLabel contact_lbl;
    private javax.swing.JTextField dob_txt;
    private javax.swing.JComboBox<String> gen_cmb;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_admintitle;
    private javax.swing.JLabel lbl_ngo;
    private javax.swing.JLabel lbl_reg;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JComboBox<String> ngo_list;
    private javax.swing.JLabel pswd_lbl;
    private javax.swing.JPasswordField pwd_txt;
    private javax.swing.JTextField reg_txt;
    private javax.swing.JButton signup_btn;
    private javax.swing.JLabel state_txt;
    private javax.swing.JTextField txt_state;
    private javax.swing.JLabel uname_lbl;
    private javax.swing.JTextField uname_txt;
    private javax.swing.JLabel zip_lbl;
    private javax.swing.JTextField zip_txt;
    // End of variables declaration//GEN-END:variables
}
