/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.NGOInterface;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.NGO.NGOClass;
import finalprojectBackend.Enterprise.NGO.Recepient;
import finalprojectUserInterface.MainJFrameForm;
import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;


/**
 *
 * @author sneha
 */
public class ReceiverSignUp extends javax.swing.JPanel {

    /**
     * Creates new form ReceiverSignUp
     */
    
    Random rand = new Random();

      
    boolean emptyValidationStatus = true;
    boolean validationCheck = true;
    
    MainJFrameForm MainLoginPage;
    //FirebaseHelper firebaseHelper;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    public ReceiverSignUp(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        for(NGOClass h: operatingSystem.getNGODirectory().getListOfNGO()){
            hospitalList.addItem(h.getNameEnterprise());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        receivertitle_lbl = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        name_lbl = new javax.swing.JLabel();
        uname_lbl = new javax.swing.JLabel();
        txtUsrName = new javax.swing.JTextField();
        pswd_lbl = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        address_lbl = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        city_lbl = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        state_lbl = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        zip_lbl = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        signup_btn = new javax.swing.JButton();
        gender_lbl = new javax.swing.JLabel();
        cmb_gender = new javax.swing.JComboBox<>();
        num_lbl = new javax.swing.JLabel();
        txt_telenum = new javax.swing.JTextField();
        dob_lbl = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        remarks_lbl = new javax.swing.JLabel();
        txt_diag = new javax.swing.JTextField();
        hospitalList = new javax.swing.JComboBox<>();
        ngo_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receivertitle_lbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        receivertitle_lbl.setText("Create Receiver Profile");
        jPanel1.add(receivertitle_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));
        jPanel1.add(txtEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 221, -1));

        name_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name_lbl.setText("Name:");
        jPanel1.add(name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        uname_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uname_lbl.setText("Username:");
        jPanel1.add(uname_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(txtUsrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 221, -1));

        pswd_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pswd_lbl.setText("Password:");
        jPanel1.add(pswd_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 221, 30));

        address_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        address_lbl.setText("Address:");
        jPanel1.add(address_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));
        jPanel1.add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 221, 30));

        city_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        city_lbl.setText("City:");
        jPanel1.add(city_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 221, -1));

        state_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        state_lbl.setText("State:");
        jPanel1.add(state_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));
        jPanel1.add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 221, 30));

        zip_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zip_lbl.setText("Zip Code:");
        jPanel1.add(zip_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 10));
        jPanel1.add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 221, 27));

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 87, -1));

        signup_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signup_btn.setText("Sign Up");
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });
        jPanel1.add(signup_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 87, -1));

        gender_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gender_lbl.setText("Gender:");
        jPanel1.add(gender_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        cmb_gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel1.add(cmb_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 221, -1));

        num_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        num_lbl.setText("Phone no.:");
        jPanel1.add(num_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        jPanel1.add(txt_telenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 221, -1));

        dob_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dob_lbl.setText("Date of Birth:");
        jPanel1.add(dob_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));
        jPanel1.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 221, -1));

        remarks_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        remarks_lbl.setText("Remarks");
        jPanel1.add(remarks_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));
        jPanel1.add(txt_diag, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 221, -1));

        hospitalList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hospitalList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jPanel1.add(hospitalList, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 221, 30));

        ngo_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ngo_lbl.setText("NGO:");
        jPanel1.add(ngo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1262, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        // TODO add your handling code here:
        
        try {
            if (EmpytyFieldValidation())
            {
                if (RegexValidation())
                {
                    String address = txtAdd.getText() + ", " + txtCity.getText() + ", " + txtState.getText() + ", " + txtZip.getText();
                    //uname, pswd, id, name, add, gender, telenum, dob diag
                    //SimpleDateFormat formatter = new SimpleDateFormat("dd-MMM-yyyy");
                    int id = rand.nextInt(99);
                    Recepient patient = new Recepient(txtUsrName.getText(), txtPass.getText(), String.valueOf(id), txtEnterpriseName.getText(), address, cmb_gender.getSelectedItem().toString(), txt_telenum.getText(),new Date() , txt_diag.getText(),hospitalList.getSelectedItem().toString());
                    System.out.println("Receiver added");

                    operatingSystem.addReceiver(patient);
                    dB4OUtility.storeSystem(operatingSystem);

                    MainJFrameForm suc = new MainJFrameForm();
                    ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                    suc.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Some Error in entered data.Please check over the red fields to know more.");
                    validationCheck=true;
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Cant be empty. Please check over the red fields to know more.");
                emptyValidationStatus=true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Receiver not registered, Try again");
            emptyValidationStatus=true;
        } 
    }//GEN-LAST:event_signup_btnActionPerformed


    private boolean RegexValidation() {
    if(!txtEnterpriseName.getText().matches("^[a-zA-Z ]+$"))
        {
            txtEnterpriseName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtEnterpriseName.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(!txt_telenum.getText().matches("^[0-9]{10}$"))
        {
            txt_telenum.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txt_telenum.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }


        if(!txtZip.getText().matches("^[0-9]{5}$"))
        {
            txtZip.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtZip.setToolTipText("Please enter a 5 digit number");
            validationCheck=false;
        }
        return validationCheck;
    }   


    private boolean EmpytyFieldValidation() {
        if(txtAdd.getText().equals(null) || txtAdd.getText().trim().isEmpty() )
        {
            txtAdd.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtAdd.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtAdd.getText().equals(null) && !txtAdd.getText().trim().isEmpty() )
        {
            txtAdd.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtCity.getText().equals(null) || txtCity.getText().trim().isEmpty() )
        {
            txtCity.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtCity.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtCity.getText().equals(null) && !txtCity.getText().trim().isEmpty() )
        {
            txtCity.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtEnterpriseName.getText().equals(null) || txtEnterpriseName.getText().trim().isEmpty() )
        {
            txtEnterpriseName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtEnterpriseName.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtEnterpriseName.getText().equals(null) && !txtEnterpriseName.getText().trim().isEmpty() )
        {
            txtEnterpriseName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtPass.getText().equals(null) || txtPass.getText().trim().isEmpty() )
        {
            txtPass.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtPass.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtPass.getText().equals(null) && !txtPass.getText().trim().isEmpty() )
        {
            txtPass.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtState.getText().equals(null) || txtState.getText().trim().isEmpty() )
        {
            txtState.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtState.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txtState.getText().equals(null) && !txtState.getText().trim().isEmpty() )
        {
            txtState.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtUsrName.getText().equals(null) || txtUsrName.getText().trim().isEmpty() )
            {
                txtUsrName.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                txtUsrName.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!txtUsrName.getText().equals(null) && !txtUsrName.getText().trim().isEmpty() )
        {
            txtUsrName.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txtZip.getText().equals(null) || txtZip.getText().trim().isEmpty() )
            {
                txtZip.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                txtZip.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!txtZip.getText().equals(null) && !txtZip.getText().trim().isEmpty() )
        {
            txtZip.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txt_diag.getText().equals(null) || txt_diag.getText().trim().isEmpty() )
            {
                txt_diag.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                txt_diag.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!txt_diag.getText().equals(null) && !txt_diag.getText().trim().isEmpty() )
        {
            txt_diag.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txt_dob.getText().equals(null) || txt_dob.getText().trim().isEmpty() )
            {
                txt_dob.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                txt_dob.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!txt_dob.getText().equals(null) && !txt_dob.getText().trim().isEmpty() )
        {
            txt_dob.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txt_telenum.getText().equals(null) || txt_telenum.getText().trim().isEmpty() )
            {
                txt_telenum.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                txt_telenum.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!txt_telenum.getText().equals(null) && !txt_telenum.getText().trim().isEmpty() )
        {
            txt_telenum.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        
        return emptyValidationStatus;
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_lbl;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel city_lbl;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JLabel dob_lbl;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JComboBox<String> hospitalList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel ngo_lbl;
    private javax.swing.JLabel num_lbl;
    private javax.swing.JLabel pswd_lbl;
    private javax.swing.JLabel receivertitle_lbl;
    private javax.swing.JLabel remarks_lbl;
    private javax.swing.JButton signup_btn;
    private javax.swing.JLabel state_lbl;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtUsrName;
    private javax.swing.JTextField txtZip;
    private javax.swing.JTextField txt_diag;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_telenum;
    private javax.swing.JLabel uname_lbl;
    private javax.swing.JLabel zip_lbl;
    // End of variables declaration//GEN-END:variables
}
