/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.AnalyticsInterface;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.Analytics.Analyst;

import finalprojectUserInterface.MainJFrameForm;
import java.awt.Color;
import java.util.Date;
import javax.swing.BorderFactory;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author sneha
 */
public class AnalystSignUp extends javax.swing.JPanel {

    /**
     * Creates new form AnalystSignUp
     */
    
    boolean ValidationStatusempty = true;
    boolean Checkvalidation = true;
    
    MainJFrameForm MainLoginPage;
    private DB4OUtility dB4OUtility;
    private OperatingSystem operatingSystem;
    public AnalystSignUp(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        analysttitle = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        unamelbl = new javax.swing.JLabel();
        user_txt = new javax.swing.JTextField();
        paswdlbl = new javax.swing.JLabel();
        pwd_txt = new javax.swing.JPasswordField();
        addresslbl = new javax.swing.JLabel();
        addr_txt = new javax.swing.JTextField();
        citylbl = new javax.swing.JLabel();
        city_txt = new javax.swing.JTextField();
        statelbl = new javax.swing.JLabel();
        statename_txt = new javax.swing.JTextField();
        ziplbl = new javax.swing.JLabel();
        zip_txt = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();
        genderlbl = new javax.swing.JLabel();
        cmb_gender = new javax.swing.JComboBox<>();
        telephnum_lbl = new javax.swing.JLabel();
        con_txt = new javax.swing.JTextField();
        dob_lbl = new javax.swing.JLabel();
        birth_txt = new javax.swing.JTextField();
        labname_lbl = new javax.swing.JLabel();
        lab_txt = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        analysttitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        analysttitle.setText("Create Analyst Profile");

        namelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namelbl.setText("Name:");

        name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_txtKeyReleased(evt);
            }
        });

        unamelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        unamelbl.setText("Username:");

        paswdlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paswdlbl.setText("Password:");

        addresslbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addresslbl.setText("Address:");

        addr_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addr_txtKeyReleased(evt);
            }
        });

        citylbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        citylbl.setText("City:");

        city_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_txtActionPerformed(evt);
            }
        });
        city_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                city_txtKeyReleased(evt);
            }
        });

        statelbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statelbl.setText("State:");

        statename_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statename_txtActionPerformed(evt);
            }
        });
        statename_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                statename_txtKeyReleased(evt);
            }
        });

        ziplbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ziplbl.setText("Zip Code:");

        zip_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zip_txtActionPerformed(evt);
            }
        });
        zip_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zip_txtKeyReleased(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        btn_signup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_signup.setText("Sign Up");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });

        genderlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        genderlbl.setText("Gender:");

        cmb_gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        telephnum_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        telephnum_lbl.setText("Phone no.:");

        con_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_txtActionPerformed(evt);
            }
        });
        con_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                con_txtKeyReleased(evt);
            }
        });

        dob_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dob_lbl.setText("Date of Birth:");

        birth_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birth_txtActionPerformed(evt);
            }
        });
        birth_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                birth_txtKeyReleased(evt);
            }
        });

        labname_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labname_lbl.setText("Lab Name:");

        lab_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_txtActionPerformed(evt);
            }
        });
        lab_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lab_txtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namelbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(analysttitle)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unamelbl)
                            .addComponent(paswdlbl)
                            .addComponent(telephnum_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(404, 404, 404)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statename_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(dob_lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(genderlbl)
                                .addGap(68, 68, 68)
                                .addComponent(cmb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(user_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(con_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(citylbl)
                                        .addComponent(addresslbl)
                                        .addComponent(statelbl))
                                    .addComponent(ziplbl)
                                    .addComponent(labname_lbl)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btn_signup)))))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {back_btn, btn_signup});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(analysttitle)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresslbl)
                    .addComponent(addr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citylbl)
                    .addComponent(city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paswdlbl)
                    .addComponent(statelbl)
                    .addComponent(statename_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ziplbl)
                    .addComponent(zip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderlbl)
                    .addComponent(cmb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephnum_lbl)
                    .addComponent(labname_lbl)
                    .addComponent(lab_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dob_lbl)
                    .addComponent(birth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signup))
                .addContainerGap(635, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {back_btn, btn_signup});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void name_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_txtKeyReleased
        
    }//GEN-LAST:event_name_txtKeyReleased

    private void addr_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addr_txtKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_addr_txtKeyReleased

    private void city_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city_txtActionPerformed

    private void city_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_city_txtKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_city_txtKeyReleased

    private void statename_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statename_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statename_txtActionPerformed

    private void statename_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statename_txtKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_statename_txtKeyReleased

    private void zip_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zip_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zip_txtActionPerformed

    private void zip_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zip_txtKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_zip_txtKeyReleased

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        try {
            if(BlankFieldValidation())
            {
                if(ValidationRegex())
                {
                    String address = addr_txt.getText() + city_txt.getText() + statename_txt.getText() + zip_txt.getText();
                    //uname, pswd, id, name, add, gender, telenum, dob
                    //(txtFullName.getText(), txtNo.getText(), address, txtUsrName.getText(), txtPass.getText());

                    Analyst tech = new Analyst(user_txt.getText(), pwd_txt.getText(), "idid", name_txt.getText(), address, cmb_gender.getSelectedItem().toString(), con_txt.getText(), new Date(),lab_txt.getText());

                    operatingSystem.addAnalyst(tech);
                    dB4OUtility.storeSystem(operatingSystem);

                    MainJFrameForm suc = new MainJFrameForm();
                    ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                    suc.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Errors in entered data,please check the red fields");
                    Checkvalidation=true;
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Please fill the red fields, data cannot be empty");
                ValidationStatusempty=true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Analyst not registered, please register !");
            ValidationStatusempty=true;
        }
       
    }//GEN-LAST:event_btn_signupActionPerformed

    private boolean ValidationRegex() {
    if(!name_txt.getText().matches("^[a-zA-Z ]+$"))
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("Enter only characters and space.");
            Checkvalidation=false;
        }
        
        if(!con_txt.getText().matches("^[0-9]{10}$"))
        {
            con_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            con_txt.setToolTipText("Enter a 10 digit number");
            Checkvalidation=false;
        }


        if(!zip_txt.getText().matches("^[0-9]{5}$"))
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            zip_txt.setToolTipText("Enter a 5 digit number");
            Checkvalidation=false;
        }

        // if(!labname_txt.getText().matches("^[0-9]{5}$"))
        // {
        //     labname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //     labname_txt.setToolTipText("Please enter a 5 digit number");
        //     Checkvalidation=false;
        // }

        return Checkvalidation;
    }   


    private boolean BlankFieldValidation() {
        if(addr_txt.getText().equals(null) || addr_txt.getText().trim().isEmpty() )
        {
            addr_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            addr_txt.setToolTipText("Field Cannot be empty");
            ValidationStatusempty= false;
        }
        if(!addr_txt.getText().equals(null) && !addr_txt.getText().trim().isEmpty() )
        {
            addr_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(city_txt.getText().equals(null) || city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            city_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatusempty= false;
        }
        if(!city_txt.getText().equals(null) && !city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(name_txt.getText().equals(null) || name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatusempty= false;
        }
        if(!name_txt.getText().equals(null) && !name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(pwd_txt.getText().equals(null) || pwd_txt.getText().trim().isEmpty() )
        {
            pwd_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            pwd_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatusempty= false;
        }
        if(!pwd_txt.getText().equals(null) && !pwd_txt.getText().trim().isEmpty() )
        {
            pwd_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(statename_txt.getText().equals(null) || statename_txt.getText().trim().isEmpty() )
        {
            statename_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            statename_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatusempty= false;
        }
        if(!statename_txt.getText().equals(null) && !statename_txt.getText().trim().isEmpty() )
        {
            statename_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(user_txt.getText().equals(null) || user_txt.getText().trim().isEmpty() )
            {
                user_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                user_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatusempty= false;
            }
        if(!user_txt.getText().equals(null) && !user_txt.getText().trim().isEmpty() )
        {
            user_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(zip_txt.getText().equals(null) || zip_txt.getText().trim().isEmpty() )
            {
                zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                zip_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatusempty= false;
            }
        if(!zip_txt.getText().equals(null) && !zip_txt.getText().trim().isEmpty() )
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(lab_txt.getText().equals(null) || lab_txt.getText().trim().isEmpty() )
            {
                lab_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lab_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatusempty= false;
            }
        if(!lab_txt.getText().equals(null) && !lab_txt.getText().trim().isEmpty() )
        {
            lab_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(con_txt.getText().equals(null) || con_txt.getText().trim().isEmpty() )
            {
                con_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                con_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatusempty= false;
            }
        if(!con_txt.getText().equals(null) && !con_txt.getText().trim().isEmpty() )
        {
            con_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(birth_txt.getText().equals(null) || birth_txt.getText().trim().isEmpty() )
            {
                birth_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                birth_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatusempty= false;
            }
        if(!birth_txt.getText().equals(null) && !birth_txt.getText().trim().isEmpty() )
        {
            birth_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        
        return ValidationStatusempty;
    }
    
    private void con_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_txtActionPerformed

    private void con_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_con_txtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_con_txtKeyReleased

    private void birth_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birth_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_txtActionPerformed

    private void birth_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birth_txtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_txtKeyReleased

    private void lab_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lab_txtActionPerformed

    private void lab_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lab_txtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lab_txtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr_txt;
    private javax.swing.JLabel addresslbl;
    private javax.swing.JLabel analysttitle;
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField birth_txt;
    private javax.swing.JButton btn_signup;
    private javax.swing.JTextField city_txt;
    private javax.swing.JLabel citylbl;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JTextField con_txt;
    private javax.swing.JLabel dob_lbl;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lab_txt;
    private javax.swing.JLabel labname_lbl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel paswdlbl;
    private javax.swing.JPasswordField pwd_txt;
    private javax.swing.JLabel statelbl;
    private javax.swing.JTextField statename_txt;
    private javax.swing.JLabel telephnum_lbl;
    private javax.swing.JLabel unamelbl;
    private javax.swing.JTextField user_txt;
    private javax.swing.JTextField zip_txt;
    private javax.swing.JLabel ziplbl;
    // End of variables declaration//GEN-END:variables
}
